-- =====================================================================
--  Leave Management System — Secure Supabase schema
--  نظام إدارة الإجازات — مخطط قاعدة البيانات الآمن
-- =====================================================================
--  HOW TO RUN
--    Supabase Dashboard -> SQL Editor -> paste this whole file -> Run.
--    It is idempotent-ish: safe to re-run (uses IF NOT EXISTS /
--    CREATE OR REPLACE). It does NOT drop your data.
--
--  SECURITY MODEL (the important part)
--    * Row Level Security (RLS) is ON for every table. Nothing is
--      readable/writable by anonymous visitors — a login is required.
--    * The frontend uses ONLY the public "anon" JWT key. That key is
--      harmless on its own: RLS + these SECURITY DEFINER functions are
--      what actually protect the data.
--    * All sensitive writes (registering a deduction, editing an
--      employee, the JSON sync) go through SECURITY DEFINER functions
--      that re-check the caller's role and enforce every business rule
--      SERVER-SIDE. A malicious user with the anon key and full source
--      code STILL cannot bypass the 40-day rule, overdraw a balance,
--      or write to tables they shouldn't. The frontend checks are just
--      UX; Postgres is the real guard.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. TABLES
-- ---------------------------------------------------------------------

-- User profiles, 1:1 with Supabase Auth users. Holds the app role.
-- (Replaces the old `custom_users` idea: passwords live in Supabase
--  Auth, hashed and salted by Supabase — never in an app table.)
create table if not exists public.profiles (
    id         uuid primary key references auth.users(id) on delete cascade,
    username   text,
    role       text not null default 'data_entry' check (role in ('admin','data_entry','viewer')),
    created_at timestamptz not null default now()
);

create table if not exists public.years (
    id   bigint generated by default as identity primary key,
    year text unique not null
);

create table if not exists public.employees (
    id                      bigint generated by default as identity primary key,
    name                    text not null,
    job_number              text default '',
    national_id             text default '',
    job_title               text default '',
    initial_carried_forward numeric not null default 0,
    over_45                 boolean not null default false,
    is_frozen               boolean not null default false,
    hire_date               text default '',
    created_at              timestamptz not null default now()
);
-- Fast lookups used by the JSON sync bridge (match by job_number).
create index if not exists employees_job_number_idx
    on public.employees (job_number) where job_number <> '';

create table if not exists public.employee_years (
    id          bigint generated by default as identity primary key,
    employee_id bigint not null references public.employees(id) on delete cascade,
    year        text not null,
    added       numeric not null default 0,
    deducted    numeric not null default 0,
    unique (employee_id, year)
);

create table if not exists public.deductions (
    id          bigint generated by default as identity primary key,
    employee_id bigint not null references public.employees(id) on delete cascade,
    year        text not null,
    start_date  text default '',
    end_date    text default '',
    days        numeric not null,
    note        text,
    created_by  text,
    created_at  timestamptz not null default now()
);

create table if not exists public.audit_log (
    id        bigint generated by default as identity primary key,
    user_id   uuid,
    username  text,
    role      text,
    action    text,
    details   text,
    timestamp timestamptz not null default now()
);

create table if not exists public.settings (
    key   text primary key,
    value text
);

-- ---------------------------------------------------------------------
-- 2. SEED DATA (only inserts when missing)
-- ---------------------------------------------------------------------
insert into public.years (year) values ('2025'), ('2026')
    on conflict (year) do nothing;

insert into public.settings (key, value) values
    ('openingBalanceDate', '2023-12-31'),
    ('system_reference_date', to_char(current_date, 'YYYY-MM-DD'))
    on conflict (key) do nothing;

-- ---------------------------------------------------------------------
-- 3. AUTH GLUE — auto-create a profile row for every new auth user.
--    Role/username come from the sign-up metadata; default data_entry.
-- ---------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, username, role)
    values (
        new.id,
        coalesce(new.raw_user_meta_data->>'username', new.email),
        coalesce(new.raw_user_meta_data->>'role', 'data_entry')
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------
-- 4. HELPERS
-- ---------------------------------------------------------------------

-- Current caller's app role. SECURITY DEFINER so it reads profiles
-- without tripping RLS (prevents policy recursion).
create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
    select role from public.profiles where id = auth.uid();
$$;

-- Internal audit writer. NOT granted to clients, so nobody can forge
-- audit entries directly — only our SECURITY DEFINER functions log.
create or replace function public.log_action(
    p_role text, p_username text, p_action text, p_details text
) returns void
language sql
security definer
set search_path = public
as $$
    insert into public.audit_log (user_id, username, role, action, details, timestamp)
    values (auth.uid(), p_username, p_role, p_action, p_details, now());
$$;

-- Serializes one employee to exactly the shape the frontend already
-- expects (mirrors the old assembleEmployee()).
create or replace function public.get_employee_json(p_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
    select jsonb_build_object(
        'id', e.id,
        'name', e.name,
        'job_number', coalesce(e.job_number, ''),
        'national_id', coalesce(e.national_id, ''),
        'job_title', coalesce(e.job_title, ''),
        'initial_carried_forward', e.initial_carried_forward,
        'over_45', e.over_45,
        'is_frozen', e.is_frozen,
        'hire_date', coalesce(e.hire_date, ''),
        'years_data', coalesce((
            select jsonb_object_agg(ey.year,
                       jsonb_build_object('added', ey.added, 'deducted', ey.deducted))
            from public.employee_years ey where ey.employee_id = e.id
        ), '{}'::jsonb),
        'deductions_history', coalesce((
            select jsonb_agg(jsonb_build_object(
                       'id', d.id, 'year', d.year, 'start', d.start_date,
                       'end', d.end_date, 'days', d.days, 'note', d.note,
                       'createdBy', d.created_by, 'createdAt', d.created_at
                   ) order by d.id)
            from public.deductions d where d.employee_id = e.id
        ), '[]'::jsonb),
        'createdAt', e.created_at
    )
    from public.employees e where e.id = p_id;
$$;

-- Weekday day-count, faithful to backend/src/utils/days.js.
-- Postgres dow: 0=Sun .. 6=Sat (same mapping as JS getDay()).
-- Quran instructors ("محفظ"/"محفظة") observe Thu+Fri; everyone else Fri+Sat.
create or replace function public.calculate_deduction_days(
    p_start text, p_end text, p_custom_holidays numeric default 0, p_job_title text default ''
) returns numeric
language plpgsql
immutable
as $$
declare
    d_start date; d_end date; cur date; cnt int := 0; wd int; weekend int[];
begin
    if p_start is null or p_end is null or p_start = '' or p_end = '' then
        return 0;
    end if;
    begin
        d_start := p_start::date;
        d_end   := p_end::date;
    exception when others then
        return 0;
    end;
    if d_end < d_start then return 0; end if;

    if p_job_title in ('محفظ', 'محفظة') then weekend := array[4,5];
    else weekend := array[5,6]; end if;

    cur := d_start;
    while cur <= d_end loop
        wd := extract(dow from cur)::int;
        if not (wd = any(weekend)) then cnt := cnt + 1; end if;
        cur := cur + 1;
    end loop;

    return greatest(0, cnt - coalesce(p_custom_holidays, 0));
end;
$$;

-- ---------------------------------------------------------------------
-- 5. BUSINESS-RULE RPCs (the only write path for sensitive data)
-- ---------------------------------------------------------------------

-- Register a deduction. Enforces, server-side and un-bypassable:
--   * caller is authenticated (admin OR data_entry)
--   * 40-day retroactive limit (dated deductions only)
--   * insufficient-balance block (dated AND dateless)
--   * timezone-proof year inference from the start date
-- p_payload keys: start, end, customHolidays, unknownDays, note
create or replace function public.register_deduction(p_employee_id bigint, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_role text; v_username text; emp public.employees%rowtype;
    v_has_dates boolean; v_has_unknown boolean;
    v_years text[]; v_latest text; v_start_year text;
    v_year text; v_days numeric; v_start text := ''; v_end text := '';
    v_retro int; v_net numeric; v_note text;
    p_start text := nullif(p_payload->>'start', '');
    p_end   text := nullif(p_payload->>'end', '');
    p_holidays numeric := coalesce((p_payload->>'customHolidays')::numeric, 0);
    p_unknown  text := nullif(trim(coalesce(p_payload->>'unknownDays','')), '');
begin
    if auth.uid() is null then raise exception 'غير مصرح'; end if;
    select role, coalesce(username, '') into v_role, v_username
        from public.profiles where id = auth.uid();
    if v_role is null then raise exception 'الحساب غير مُهيأ'; end if;

    select * into emp from public.employees where id = p_employee_id;
    if not found then raise exception 'الموظف غير موجود'; end if;

    v_note := nullif(left(trim(coalesce(p_payload->>'note','')), 500), '');

    select array_agg(year order by cast(year as integer)) into v_years from public.years;
    if v_years is null then raise exception 'لا توجد سنة مالية نشطة لتسجيل الخصم'; end if;
    v_latest := v_years[array_length(v_years, 1)];

    v_has_dates   := (p_start is not null and p_end is not null);
    v_has_unknown := (p_unknown is not null);

    if v_has_dates then
        v_start_year := split_part(p_start, '-', 1);
        if not (v_start_year = any(v_years)) then
            raise exception 'لا توجد سنة مالية نشطة مطابقة لتاريخ البداية (%)', v_start_year;
        end if;
        v_year := v_start_year;
        v_days := public.calculate_deduction_days(p_start, p_end, p_holidays, coalesce(emp.job_title,''));
        if v_days <= 0 then
            raise exception 'يجب أن يكون عدد أيام الخصم أكبر من صفر';
        end if;
        -- "Today" must be Libya's calendar date, not the database server's.
        -- Supabase runs on UTC, so between 00:00 and 02:00 Libya time
        -- `current_date` is still yesterday — silently widening the 40-day
        -- window to 41 during those hours and disagreeing with the
        -- frontend's Africa/Tripoli check.
        v_retro := ((now() at time zone 'Africa/Tripoli')::date - p_start::date);
        if v_retro > 40 then
            raise exception 'لا يمكن تسجيل إجازة بتاريخ رجعي يتجاوز 40 يوماً من تاريخ النظام الحالي.';
        end if;
        v_start := p_start; v_end := p_end;
    elsif v_has_unknown then
        v_days := p_unknown::numeric;
        if not (v_days > 0) then
            raise exception 'يرجى إدخال عدد أيام صحيح أكبر من صفر';
        end if;
        v_year := v_latest;
    else
        raise exception 'يرجى تحديد تاريخ البداية والنهاية أو عدد أيام الخصم';
    end if;

    -- Insufficient-balance protection (computed BEFORE the new year row is
    -- inserted, matching the original Express behavior exactly).
    select coalesce(emp.initial_carried_forward, 0)
         + coalesce(sum(coalesce(added,0) - coalesce(deducted,0)), 0)
      into v_net
      from public.employee_years where employee_id = emp.id;
    if v_days > v_net then
        raise exception 'فشلت العملية: رصيد الموظف الحالي غير كافٍ لتغطية عدد أيام الخصم المطلوبة.';
    end if;

    insert into public.employee_years (employee_id, year, added, deducted)
    values (emp.id, v_year, case when emp.over_45 then 45 else 30 end, 0)
    on conflict (employee_id, year) do nothing;

    update public.employee_years set deducted = deducted + v_days
        where employee_id = emp.id and year = v_year;

    insert into public.deductions (employee_id, year, start_date, end_date, days, note, created_by, created_at)
    values (emp.id, v_year, v_start, v_end, v_days, v_note, v_username, now());

    perform public.log_action(v_role, v_username, 'تسجيل خصم إجازة',
        format('تم خصم %s يوم من رصيد %s لسنة %s%s', v_days, emp.name, v_year,
               case when v_has_dates then '' else ' (بدون تاريخ محدد)' end));

    return jsonb_build_object('employee', public.get_employee_json(emp.id));
end;
$$;

-- Delete a deduction and restore the counter (ADMIN only).
create or replace function public.delete_deduction(p_deduction_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_role text; v_username text; d public.deductions%rowtype;
begin
    select role, coalesce(username,'') into v_role, v_username
        from public.profiles where id = auth.uid();
    if v_role is distinct from 'admin' then
        raise exception 'هذه العملية مقصورة على المدير';
    end if;
    select * into d from public.deductions where id = p_deduction_id;
    if not found then raise exception 'سجل الخصم غير موجود'; end if;

    update public.employee_years set deducted = greatest(0, deducted - d.days)
        where employee_id = d.employee_id and year = d.year;
    delete from public.deductions where id = d.id;

    perform public.log_action(v_role, v_username, 'حذف خصم إجازة',
        format('تم حذف خصم %s يوم', d.days));
    return jsonb_build_object('employee', public.get_employee_json(d.employee_id));
end;
$$;

-- Create an employee, with optional paper-inventory reconciliation
-- (ADMIN only). p_payload mirrors the old POST /employees body.
create or replace function public.create_employee(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_role text; v_username text;
    v_name text; v_hire text; v_recon_note text;
    v_over45 boolean; v_initial numeric;
    v_has_remaining boolean; v_remaining numeric;
    v_years text[]; v_current text; v_year text;
    v_added numeric; v_current_added numeric; v_available numeric; v_consumed numeric;
    v_new_id bigint;
begin
    select role, coalesce(username,'') into v_role, v_username
        from public.profiles where id = auth.uid();
    if v_role is distinct from 'admin' then
        raise exception 'هذه العملية مقصورة على المدير';
    end if;

    v_name := trim(coalesce(p_payload->>'name', ''));
    if v_name = '' then raise exception 'يرجى إدخال اسم الموظف كاملاً'; end if;

    v_hire := trim(coalesce(p_payload->>'hire_date', ''));
    if v_hire <> '' and v_hire !~ '^\d{4}-\d{2}-\d{2}$' then
        raise exception 'تاريخ المباشرة يجب أن يكون بصيغة YYYY-MM-DD';
    end if;

    v_over45  := coalesce((p_payload->>'over_45')::boolean, false);
    v_initial := coalesce((p_payload->>'initial_carried_forward')::numeric, 0);
    v_recon_note := left(trim(coalesce(p_payload->>'reconciliationNote','')), 500);

    v_has_remaining := nullif(trim(coalesce(p_payload->>'actualRemainingBalance','')), '') is not null;
    if v_has_remaining then v_remaining := (p_payload->>'actualRemainingBalance')::numeric; end if;

    select array_agg(year order by cast(year as integer)) into v_years from public.years;
    v_current := case when array_length(v_years,1) is null then null
                      else v_years[array_length(v_years,1)] end;

    insert into public.employees
        (name, job_number, national_id, job_title, initial_carried_forward, over_45, is_frozen, hire_date, created_at)
    values (
        v_name,
        trim(coalesce(p_payload->>'job_number','')),
        trim(coalesce(p_payload->>'national_id','')),
        trim(coalesce(p_payload->>'job_title','')),
        v_initial, v_over45, false, v_hire, now()
    ) returning id into v_new_id;

    v_current_added := case when v_over45 then 45 else 30 end;
    if v_years is not null then
        foreach v_year in array v_years loop
            v_added := nullif(p_payload->'years_data'->v_year->>'added', '')::numeric;
            if v_added is null then v_added := case when v_over45 then 45 else 30 end; end if;
            insert into public.employee_years (employee_id, year, added, deducted)
            values (v_new_id, v_year, v_added, 0)
            on conflict (employee_id, year) do update set added = excluded.added;
            if v_year = v_current then v_current_added := v_added; end if;
        end loop;
    end if;

    if v_has_remaining and v_current is not null then
        v_available := v_initial + v_current_added;
        v_consumed  := v_available - v_remaining;
        if v_consumed > 0 then
            update public.employee_years set deducted = deducted + v_consumed
                where employee_id = v_new_id and year = v_current;
            insert into public.deductions (employee_id, year, start_date, end_date, days, note, created_by, created_at)
            values (v_new_id, v_current, '', '', v_consumed, v_recon_note, v_username, now());
        end if;
    end if;

    perform public.log_action(v_role, v_username, 'إضافة موظف',
        format('تمت إضافة الموظف: %s', v_name));
    return jsonb_build_object('employee', public.get_employee_json(v_new_id));
end;
$$;

-- Edit an employee, with optional edit-time reconciliation (ADMIN only).
create or replace function public.update_employee(p_id bigint, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_role text; v_username text; emp public.employees%rowtype;
    v_name text; v_hire text; v_recon_note text;
    v_initial numeric; v_has_remaining boolean; v_remaining numeric;
    v_years text[]; v_current text; v_year text; v_added numeric;
    v_net numeric; v_diff numeric; v_recon_days numeric := 0;
    yd_key text; yd_val jsonb;
begin
    select role, coalesce(username,'') into v_role, v_username
        from public.profiles where id = auth.uid();
    if v_role is distinct from 'admin' then
        raise exception 'هذه العملية مقصورة على المدير';
    end if;

    select * into emp from public.employees where id = p_id;
    if not found then raise exception 'الموظف غير موجود'; end if;

    v_name := trim(coalesce(p_payload->>'name',''));
    if v_name = '' then raise exception 'يرجى إدخال اسم الموظف كاملاً'; end if;
    v_hire := trim(coalesce(p_payload->>'hire_date',''));
    if v_hire <> '' and v_hire !~ '^\d{4}-\d{2}-\d{2}$' then
        raise exception 'تاريخ المباشرة يجب أن يكون بصيغة YYYY-MM-DD';
    end if;

    v_initial := coalesce((p_payload->>'initial_carried_forward')::numeric, 0);
    v_recon_note := left(trim(coalesce(p_payload->>'reconciliationNote','')), 500);
    v_has_remaining := nullif(trim(coalesce(p_payload->>'actualRemainingBalance','')), '') is not null;
    if v_has_remaining then v_remaining := (p_payload->>'actualRemainingBalance')::numeric; end if;

    update public.employees set
        name = v_name,
        job_number  = trim(coalesce(p_payload->>'job_number','')),
        national_id = trim(coalesce(p_payload->>'national_id','')),
        job_title   = trim(coalesce(p_payload->>'job_title','')),
        initial_carried_forward = v_initial,
        over_45   = coalesce((p_payload->>'over_45')::boolean, false),
        hire_date = v_hire
    where id = p_id;

    if p_payload ? 'years_data' then
        for yd_key, yd_val in select key, value from jsonb_each(p_payload->'years_data') loop
            v_added := nullif(yd_val->>'added', '')::numeric;
            if v_added is not null then
                insert into public.employee_years (employee_id, year, added, deducted)
                values (p_id, yd_key, v_added, 0)
                on conflict (employee_id, year) do update set added = excluded.added;
            end if;
        end loop;
    end if;

    if v_has_remaining then
        select array_agg(year order by cast(year as integer)) into v_years from public.years;
        v_current := case when array_length(v_years,1) is null then null
                          else v_years[array_length(v_years,1)] end;
        if v_current is not null then
            select v_initial + coalesce(sum(coalesce(added,0) - coalesce(deducted,0)), 0)
                into v_net from public.employee_years where employee_id = p_id;
            v_diff := v_net - v_remaining;
            if v_diff > 0 then
                update public.employee_years set deducted = deducted + v_diff
                    where employee_id = p_id and year = v_current;
                insert into public.deductions (employee_id, year, start_date, end_date, days, note, created_by, created_at)
                values (p_id, v_current, '', '', v_diff, v_recon_note, v_username, now());
                v_recon_days := v_diff;
            end if;
        end if;
    end if;

    perform public.log_action(v_role, v_username, 'تعديل موظف',
        format('تم تعديل الموظف: %s', v_name));
    return jsonb_build_object('employee', public.get_employee_json(p_id),
                              'reconciliationDays', v_recon_days);
end;
$$;

-- Toggle frozen status (ADMIN only). Reversible; deletes nothing.
create or replace function public.toggle_employee_freeze(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_role text; v_username text; emp public.employees%rowtype;
begin
    select role, coalesce(username,'') into v_role, v_username
        from public.profiles where id = auth.uid();
    if v_role is distinct from 'admin' then
        raise exception 'هذه العملية مقصورة على المدير';
    end if;
    select * into emp from public.employees where id = p_id;
    if not found then raise exception 'الموظف غير موجود'; end if;

    update public.employees set is_frozen = not is_frozen where id = p_id;
    perform public.log_action(v_role, v_username,
        case when emp.is_frozen then 'إلغاء تجميد موظف' else 'تجميد موظف' end,
        format('الموظف: %s', emp.name));
    return jsonb_build_object('employee', public.get_employee_json(p_id));
end;
$$;

-- THE HYBRID JSON SYNC BRIDGE (مزامنة السحابة). ADMIN only.
-- Merges an offline export (same shape as the app's JSON export:
-- {years, employees:[{...,years_data,deductions_history}], settings})
-- into the cloud DB via UPSERT — matching employees by id, then by
-- job_number, so job numbers and ids are preserved and no duplicates
-- are created. Deductions merge by id (existing ids are left as-is).
create or replace function public.sync_employees(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_role text; v_username text;
    v_years jsonb; v_settings jsonb;
    emp jsonb; ded jsonb; yv text; yd_key text; yd_val jsonb;
    v_target bigint; v_created int := 0; v_updated int := 0; v_ded int := 0;
begin
    select role, coalesce(username,'') into v_role, v_username
        from public.profiles where id = auth.uid();
    if v_role is distinct from 'admin' then
        raise exception 'هذه العملية مقصورة على المدير';
    end if;

    v_years    := coalesce(p_payload->'years', '[]'::jsonb);
    v_settings := p_payload->'settings';

    for yv in select value from jsonb_array_elements_text(v_years) loop
        if yv ~ '^\d{4}$' then
            insert into public.years (year) values (yv) on conflict (year) do nothing;
        end if;
    end loop;

    for emp in select value from jsonb_array_elements(coalesce(p_payload->'employees','[]'::jsonb)) loop
        if coalesce(trim(emp->>'name'), '') = '' then continue; end if;

        v_target := null;
        if nullif(emp->>'id','') is not null then
            select id into v_target from public.employees where id = (emp->>'id')::bigint;
        end if;
        if v_target is null and coalesce(trim(emp->>'job_number'),'') <> '' then
            select id into v_target from public.employees
                where job_number = trim(emp->>'job_number') limit 1;
        end if;

        if v_target is null then
            insert into public.employees
                (id, name, job_number, national_id, job_title, initial_carried_forward, over_45, is_frozen, hire_date, created_at)
            values (
                coalesce(nullif(emp->>'id','')::bigint,
                         nextval(pg_get_serial_sequence('public.employees','id'))),
                trim(emp->>'name'),
                coalesce(trim(emp->>'job_number'),''),
                coalesce(trim(emp->>'national_id'),''),
                coalesce(trim(emp->>'job_title'),''),
                coalesce((emp->>'initial_carried_forward')::numeric, 0),
                coalesce((emp->>'over_45')::boolean, false),
                coalesce((emp->>'is_frozen')::boolean, false),
                coalesce(trim(emp->>'hire_date'),''),
                coalesce((emp->>'createdAt')::timestamptz, now())
            ) returning id into v_target;
            v_created := v_created + 1;
        else
            update public.employees set
                name = trim(emp->>'name'),
                job_number  = coalesce(trim(emp->>'job_number'), job_number),
                national_id = coalesce(trim(emp->>'national_id'), national_id),
                job_title   = coalesce(trim(emp->>'job_title'), job_title),
                initial_carried_forward = coalesce((emp->>'initial_carried_forward')::numeric, initial_carried_forward),
                over_45   = coalesce((emp->>'over_45')::boolean, over_45),
                is_frozen = coalesce((emp->>'is_frozen')::boolean, is_frozen),
                hire_date = coalesce(trim(emp->>'hire_date'), hire_date)
            where id = v_target;
            v_updated := v_updated + 1;
        end if;

        if emp ? 'years_data' then
            for yd_key, yd_val in select key, value from jsonb_each(emp->'years_data') loop
                if yd_key ~ '^\d{4}$' then
                    insert into public.years (year) values (yd_key) on conflict (year) do nothing;
                    insert into public.employee_years (employee_id, year, added, deducted)
                    values (v_target, yd_key,
                            coalesce((yd_val->>'added')::numeric, 0),
                            coalesce((yd_val->>'deducted')::numeric, 0))
                    on conflict (employee_id, year)
                        do update set added = excluded.added, deducted = excluded.deducted;
                end if;
            end loop;
        end if;

        if emp ? 'deductions_history' then
            for ded in select value from jsonb_array_elements(emp->'deductions_history') loop
                if not (coalesce((ded->>'days')::numeric, 0) > 0) then continue; end if;
                if nullif(ded->>'id','') is not null then
                    insert into public.deductions
                        (id, employee_id, year, start_date, end_date, days, note, created_by, created_at)
                    values ((ded->>'id')::bigint, v_target, coalesce(ded->>'year',''),
                            coalesce(ded->>'start',''), coalesce(ded->>'end',''),
                            (ded->>'days')::numeric,
                            nullif(left(trim(coalesce(ded->>'note','')),500),''),
                            ded->>'createdBy', coalesce((ded->>'createdAt')::timestamptz, now()))
                    on conflict (id) do nothing;
                else
                    insert into public.deductions
                        (employee_id, year, start_date, end_date, days, note, created_by, created_at)
                    values (v_target, coalesce(ded->>'year',''), coalesce(ded->>'start',''),
                            coalesce(ded->>'end',''), (ded->>'days')::numeric,
                            nullif(left(trim(coalesce(ded->>'note','')),500),''),
                            ded->>'createdBy', coalesce((ded->>'createdAt')::timestamptz, now()));
                end if;
                v_ded := v_ded + 1;
            end loop;
        end if;
    end loop;

    if v_settings is not null and (v_settings->>'openingBalanceDate') ~ '^\d{4}-\d{2}-\d{2}$' then
        insert into public.settings (key, value)
        values ('openingBalanceDate', v_settings->>'openingBalanceDate')
        on conflict (key) do update set value = excluded.value;
    end if;

    -- keep the identity sequences ahead of any explicit ids we inserted
    perform setval(pg_get_serial_sequence('public.employees','id'),
                   (select coalesce(max(id),1) from public.employees),
                   (select count(*) > 0 from public.employees));
    perform setval(pg_get_serial_sequence('public.deductions','id'),
                   (select coalesce(max(id),1) from public.deductions),
                   (select count(*) > 0 from public.deductions));

    perform public.log_action(v_role, v_username, 'مزامنة سحابية (استيراد JSON)',
        format('موظفون جدد: %s، تحديثات: %s، خصومات: %s', v_created, v_updated, v_ded));
    return jsonb_build_object('created', v_created, 'updated', v_updated, 'deductions', v_ded);
end;
$$;

-- Read the whole roster in one round-trip (both roles). Same shape the
-- old GET /employees returned: { employees:[...], years:[...] }.
create or replace function public.list_employees()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
    select jsonb_build_object(
        'employees', coalesce(
            (select jsonb_agg(public.get_employee_json(e.id) order by e.id) from public.employees e),
            '[]'::jsonb),
        'years', coalesce(
            (select jsonb_agg(y.year order by cast(y.year as integer)) from public.years y),
            '[]'::jsonb)
    );
$$;

-- Full JSON export (ADMIN only) — mirrors the old GET /backup/export.
create or replace function public.export_all()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare v_role text;
begin
    select role into v_role from public.profiles where id = auth.uid();
    if v_role is distinct from 'admin' then
        raise exception 'هذه العملية مقصورة على المدير';
    end if;
    return jsonb_build_object(
        'version', 1,
        'exportedAt', now(),
        'years', coalesce((select jsonb_agg(year order by cast(year as integer)) from public.years), '[]'::jsonb),
        'employees', coalesce((select jsonb_agg(public.get_employee_json(id) order by id) from public.employees), '[]'::jsonb),
        'settings', coalesce((select jsonb_object_agg(key, value) from public.settings), '{}'::jsonb)
    );
end;
$$;

-- Bulk onboarding from a parsed Excel/CSV (ADMIN only) — mirrors the old
-- POST /employees/bulk. Rows need only a name; everything else defaults.
create or replace function public.bulk_add_employees(p_rows jsonb, p_note text default '')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_role text; v_username text; v_years text[]; v_current text;
    r jsonb; v_name text; v_id bigint; v_note text;
    v_created int := 0; v_skipped int := 0; v_reconciled int := 0;
    v_remaining numeric; v_consumed numeric; v_ids bigint[] := '{}';
begin
    select role, coalesce(username,'') into v_role, v_username
        from public.profiles where id = auth.uid();
    if v_role is distinct from 'admin' then
        raise exception 'هذه العملية مقصورة على المدير';
    end if;
    if jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) = 0 then
        raise exception 'لا توجد بيانات موظفين صالحة للاستيراد';
    end if;

    v_note := left(trim(coalesce(p_note,'')), 500);
    select array_agg(year order by cast(year as integer)) into v_years from public.years;
    v_current := case when array_length(v_years,1) is null then null
                      else v_years[array_length(v_years,1)] end;

    for r in select value from jsonb_array_elements(p_rows) loop
        v_name := trim(coalesce(r->>'name',''));
        if v_name = '' then v_skipped := v_skipped + 1; continue; end if;

        insert into public.employees
            (name, job_number, national_id, job_title, initial_carried_forward, over_45, is_frozen, created_at)
        values (v_name, coalesce(trim(r->>'job_number'),''), coalesce(trim(r->>'national_id'),''),
                coalesce(trim(r->>'job_title'),''), 0, false, false, now())
        returning id into v_id;

        if v_years is not null then
            insert into public.employee_years (employee_id, year, added, deducted)
            select v_id, y, 30, 0 from unnest(v_years) as y
            on conflict (employee_id, year) do nothing;
        end if;

        if nullif(trim(coalesce(r->>'remainingBalance','')),'') is not null and v_current is not null then
            v_remaining := (r->>'remainingBalance')::numeric;
            v_consumed  := 30 - v_remaining;  -- availableTotal defaults to 30 for bulk rows
            if v_consumed > 0 then
                update public.employee_years set deducted = deducted + v_consumed
                    where employee_id = v_id and year = v_current;
                insert into public.deductions (employee_id, year, start_date, end_date, days, note, created_by, created_at)
                values (v_id, v_current, '', '', v_consumed, v_note, v_username, now());
                v_reconciled := v_reconciled + 1;
            end if;
        end if;

        v_ids := array_append(v_ids, v_id);
        v_created := v_created + 1;
    end loop;

    perform setval(pg_get_serial_sequence('public.employees','id'),
                   (select coalesce(max(id),1) from public.employees),
                   (select count(*) > 0 from public.employees));
    perform public.log_action(v_role, v_username, 'استيراد جماعي للموظفين',
        format('تمت إضافة %s موظف (تخطي %s، تسوية %s)', v_created, v_skipped, v_reconciled));

    return jsonb_build_object(
        'created', v_created, 'skipped', v_skipped, 'reconciled', v_reconciled,
        'employees', coalesce(
            (select jsonb_agg(public.get_employee_json(id) order by id)
             from public.employees where id = any(v_ids)), '[]'::jsonb)
    );
end;
$$;

-- Add a financial year and grant it to every employee (ADMIN only) —
-- mirrors POST /years (over-45 employees get 45, others p_default_days).
create or replace function public.add_year(p_year text, p_default_days numeric default 30)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_role text; v_username text; v_year text; v_default numeric;
begin
    select role, coalesce(username,'') into v_role, v_username
        from public.profiles where id = auth.uid();
    if v_role is distinct from 'admin' then raise exception 'هذه العملية مقصورة على المدير'; end if;
    v_year := trim(coalesce(p_year, ''));
    if v_year !~ '^\d{4}$' then raise exception 'يرجى إدخال سنة مالية صحيحة'; end if;
    if exists (select 1 from public.years where year = v_year) then
        raise exception 'هذه السنة مسجلة مسبقاً';
    end if;
    v_default := coalesce(p_default_days, 30);
    insert into public.years (year) values (v_year);
    insert into public.employee_years (employee_id, year, added, deducted)
    select id, v_year, case when over_45 then 45 else v_default end, 0 from public.employees
    on conflict (employee_id, year) do nothing;
    perform public.log_action(v_role, v_username, 'إضافة سنة مالية', format('السنة: %s', v_year));
    return jsonb_build_object('years',
        coalesce((select jsonb_agg(year order by cast(year as integer)) from public.years), '[]'::jsonb));
end;
$$;

-- Delete a financial year and its dependent rows (ADMIN only) — mirrors
-- DELETE /years/:year. Refuses to remove the last remaining year.
create or replace function public.delete_year(p_year text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_role text; v_username text; v_year text; v_count int;
begin
    select role, coalesce(username,'') into v_role, v_username
        from public.profiles where id = auth.uid();
    if v_role is distinct from 'admin' then raise exception 'هذه العملية مقصورة على المدير'; end if;
    v_year := trim(coalesce(p_year, ''));
    if not exists (select 1 from public.years where year = v_year) then
        raise exception 'هذه السنة غير موجودة';
    end if;
    select count(*) into v_count from public.years;
    if v_count <= 1 then raise exception 'لا يمكن حذف آخر سنة مالية متبقية في النظام'; end if;
    delete from public.deductions where year = v_year;
    delete from public.employee_years where year = v_year;
    delete from public.years where year = v_year;
    perform public.log_action(v_role, v_username, 'حذف سنة مالية', format('السنة: %s', v_year));
    return jsonb_build_object('years',
        coalesce((select jsonb_agg(year order by cast(year as integer)) from public.years), '[]'::jsonb));
end;
$$;

-- ---------------------------------------------------------------------
-- 6. ROW LEVEL SECURITY
-- ---------------------------------------------------------------------
alter table public.profiles       enable row level security;
alter table public.years          enable row level security;
alter table public.employees      enable row level security;
alter table public.employee_years enable row level security;
alter table public.deductions     enable row level security;
alter table public.audit_log      enable row level security;
alter table public.settings       enable row level security;

-- profiles: read own row (or all, if admin); only admin may modify.
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated
    using (id = auth.uid() or public.current_app_role() = 'admin');
drop policy if exists profiles_admin_write on public.profiles;
create policy profiles_admin_write on public.profiles for all to authenticated
    using (public.current_app_role() = 'admin')
    with check (public.current_app_role() = 'admin');

-- employees / years / settings: any logged-in user may READ; only admin
-- may write directly. (Deductions & reconciliation still go via RPCs.)
drop policy if exists employees_select on public.employees;
create policy employees_select on public.employees for select to authenticated using (true);
drop policy if exists employees_admin_write on public.employees;
create policy employees_admin_write on public.employees for all to authenticated
    using (public.current_app_role() = 'admin')
    with check (public.current_app_role() = 'admin');

drop policy if exists years_select on public.years;
create policy years_select on public.years for select to authenticated using (true);
drop policy if exists years_admin_write on public.years;
create policy years_admin_write on public.years for all to authenticated
    using (public.current_app_role() = 'admin')
    with check (public.current_app_role() = 'admin');

drop policy if exists settings_select on public.settings;
create policy settings_select on public.settings for select to authenticated using (true);
drop policy if exists settings_admin_write on public.settings;
create policy settings_admin_write on public.settings for all to authenticated
    using (public.current_app_role() = 'admin')
    with check (public.current_app_role() = 'admin');

-- employee_years & deductions: READ-ONLY to clients. Every write happens
-- inside a SECURITY DEFINER function, so counters can never desync and
-- business rules can never be bypassed from the browser.
drop policy if exists employee_years_select on public.employee_years;
create policy employee_years_select on public.employee_years for select to authenticated using (true);

drop policy if exists deductions_select on public.deductions;
create policy deductions_select on public.deductions for select to authenticated using (true);

-- audit_log: admin may read; nobody writes directly (log_action only).
drop policy if exists audit_admin_select on public.audit_log;
create policy audit_admin_select on public.audit_log for select to authenticated
    using (public.current_app_role() = 'admin');

-- ---------------------------------------------------------------------
-- 7. GRANTS
--    Broad table grants + RLS = idiomatic Supabase. Anonymous role gets
--    nothing (login required). Functions are granted individually so the
--    audit writer / internal helpers stay uncallable by clients.
-- ---------------------------------------------------------------------
grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on function public.log_action(text,text,text,text)      from public;
revoke all on function public.get_employee_json(bigint)            from public;
revoke all on function public.handle_new_user()                    from public;

grant execute on function public.current_app_role()                              to authenticated;
grant execute on function public.register_deduction(bigint, jsonb)               to authenticated;
grant execute on function public.delete_deduction(bigint)                        to authenticated;
grant execute on function public.create_employee(jsonb)                          to authenticated;
grant execute on function public.update_employee(bigint, jsonb)                  to authenticated;
grant execute on function public.toggle_employee_freeze(bigint)                  to authenticated;
grant execute on function public.sync_employees(jsonb)                           to authenticated;
grant execute on function public.list_employees()                                to authenticated;
grant execute on function public.export_all()                                    to authenticated;
grant execute on function public.bulk_add_employees(jsonb, text)                 to authenticated;
grant execute on function public.add_year(text, numeric)                         to authenticated;
grant execute on function public.delete_year(text)                               to authenticated;

-- ---- User management RPCs (SECURITY DEFINER, admin-only UI) ----------
create or replace function public.create_auth_user(
    p_email    text,
    p_password text,
    p_role     text default 'data_entry'
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user_id uuid;
    v_enc_pw  text;
begin
    if p_role not in ('data_entry', 'viewer') then
        raise exception 'الصلاحية غير صالحة. يجب أن تكون data_entry أو viewer.';
    end if;
    if exists (select 1 from auth.users where email = p_email) then
        raise exception 'المستخدم % موجود مسبقاً', p_email;
    end if;

    v_user_id := gen_random_uuid();
    v_enc_pw  := crypt(p_password, gen_salt('bf'));

    insert into auth.users (
        id, instance_id, email, encrypted_password, email_confirmed_at,
        raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
        confirmation_token, email_change, email_change_token_new, recovery_token,
        is_super_admin, role
    ) values (
        v_user_id,
        '00000000-0000-0000-0000-000000000000',
        p_email,
        v_enc_pw,
        now(),
        jsonb_build_object('provider', 'email', 'providers', array['email']),
        jsonb_build_object('role', p_role),
        now(), now(),
        '', '', '', '',
        false, 'authenticated'
    );

    insert into auth.identities (
        id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
    ) values (
        v_user_id,
        v_user_id,
        jsonb_build_object('sub', v_user_id, 'email', p_email),
        'email',
        p_email,
        now(), now(), now()
    );

    return json_build_object('id', v_user_id::text, 'email', p_email, 'role', p_role);
end;
$$;

create or replace function public.delete_auth_user(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if not exists (select 1 from auth.users where id = p_id) then
        raise exception 'المستخدم غير موجود';
    end if;
    delete from auth.users where id = p_id;
end;
$$;

grant execute on function public.create_auth_user(text, text, text)   to authenticated;
grant execute on function public.delete_auth_user(uuid)               to authenticated;

-- =====================================================================
--  DONE. Next: create your first admin (see MIGRATION.md, step 3).
-- =====================================================================
