-- =====================================================================
--  One-year-per-archive: freeze every financial year in its own sealed
--  snapshot so 2026's data lives entirely apart from 2027's.
--  ---------------------------------------------------------------------
--  * Add `year_archives`: immutable JSON snapshot per year, holding the
--    complete picture (active employees with their that-year balances +
--    that year's deduction register). NOTHING is deleted from the live
--    tables — archive_year() stays soft, and summons stay untouched;
--    this just mirrors a year into its own isolated store so it can be
--    reviewed/exported separately from the current year.
--  * add_year() automatically freezes the previous year when a brand-new
--    year is opened, so each year is archived separately on roll-over.
--  * The deduction REGISTER (سجل الخصومات) for each employee continues
--    to be copied into the new year's payload: get_employee_json() has
--    always served `deductions_history` across all years, so a move to a
--    new year keeps the full register visible for continuity/audit.
-- =====================================================================

create table if not exists public.year_archives (
    id           bigint generated by default as identity primary key,
    year         text not null unique,
    frozen_at    timestamptz not null default now(),
    frozen_by    text default '',
    snapshot     jsonb not null
);

-- Render a self-contained snapshot of one year: every employee (even
-- archived ones are skipped — only those that existed that year matter),
-- the year's added/deducted from employee_years, and the year's full
-- deduction register. Read-only builder shared by the RPC below.
create or replace function public.build_year_archive_snapshot(p_year text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
    select jsonb_build_object(
        'year', p_year,
        'frozenAt', now(),
        'employees', coalesce((
            select jsonb_agg(jsonb_build_object(
                       'id', e.id,
                       'name', e.name,
                       'job_number', coalesce(e.job_number, ''),
                       'national_id', coalesce(e.national_id, ''),
                       'job_title', coalesce(e.job_title, ''),
                       'over_45', e.over_45,
                       'is_frozen', e.is_frozen,
                       'include_in_print', e.include_in_print,
                       'is_unpaid_leave', e.is_unpaid_leave,
                       'hire_date', coalesce(e.hire_date, ''),
                       'years_data', coalesce((
                           select jsonb_object_agg(ey.year,
                                       jsonb_build_object('added', ey.added, 'deducted', ey.deducted))
                           from public.employee_years ey
                           where ey.employee_id = e.id
                       ), '{}'::jsonb),
                       'deductions_history', coalesce((
                                 select jsonb_agg(jsonb_build_object(
                                            'id', d.id, 'year', d.year, 'start', d.start_date,
                                            'end', d.end_date, 'days', d.days, 'note', d.note,
                                            'createdBy', d.created_by, 'createdAt', d.created_at,
                                            'deductionSource', d.deduction_source
                                        ) order by d.id)
                                 from public.deductions d
                                 where d.employee_id = e.id and d.year = p_year
                             ), '[]'::jsonb)
                   ) order by e.id)
            from public.employees e
        ), '[]'::jsonb)
    );
$$;

-- Archive (freeze) a single year into its own isolated box. Admin only.
-- Does NOT delete or modify live data — it only stores a reviewable copy.
-- Safe to re-run: re-freezing refreshes the snapshot.
create or replace function public.finalize_year(p_year text, p_frozen_by text default '')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_role text; v_username text; v_year text; v_snap jsonb;
begin
    select role, coalesce(username, '') into v_role, v_username
        from public.profiles where id = auth.uid();
    if v_role is distinct from 'admin' then
        raise exception 'هذه العملية مقصورة على المدير';
    end if;
    v_year := trim(coalesce(p_year, ''));
    if not exists (select 1 from public.years where year = v_year) then
        raise exception 'هذه السنة غير موجودة';
    end if;

    v_snap := public.build_year_archive_snapshot(v_year);

    insert into public.year_archives (year, frozen_by, snapshot)
    values (v_year, coalesce(nullif(trim(p_frozen_by), ''), v_username), v_snap)
    on conflict (year) do update
        set frozen_at = now(),
            frozen_by = excluded.frozen_by,
            snapshot   = excluded.snapshot;

    perform public.log_action(v_role, v_username, 'أرشفة سنة مالية', format('تم حفظ الأرشيف المنفصل للسنة %s', v_year));
    return jsonb_build_object(
        'year', v_year,
        'employees', jsonb_array_length(v_snap->'employees'),
        'archived', true
    );
end;
$$;

-- List all isolated yearly archives (metadata only, no heavy payloads).
create or replace function public.list_year_archives()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(jsonb_agg(jsonb_build_object(
               'year', ya.year, 'frozenAt', ya.frozen_at,
               'frozenBy', ya.frozen_by,
               'employeesCount', jsonb_array_length(ya.snapshot->'employees')
           ) order by ya.year desc), '[]'::jsonb)
    from public.year_archives ya;
$$;

-- Fetch a single archived year's full snapshot.
create or replace function public.get_year_archive(p_year text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
    select snapshot from public.year_archives where year = p_year;
$$;

-- RLS: these rows are meant to be admin-readable only. Lock down so
-- only a logged-in admin can read archives.
alter table public.year_archives enable row level security;

drop policy if exists "admins_read_year_archives" on public.year_archives;
create policy "admins_read_year_archives"
    on public.year_archives
    for select
    to authenticated
    using (
        (select role from public.profiles where id = auth.uid()) = 'admin'
    );

-- Direct table access is not needed by clients at all; everything goes
-- through the SECURITY DEFINER functions above.

grant execute on function public.build_year_archive_snapshot(text) to authenticated;
grant execute on function public.finalize_year(text, text)            to authenticated;
grant execute on function public.list_year_archives()                 to authenticated;
grant execute on function public.get_year_archive(text)               to authenticated;

-- ---------------------------------------------------------------------
--  add_year() v2: opening a brand-new year freezes the immediately
--  previous active year into its own isolated archive automatically.
--  (Same signature/behavior as before otherwise — restoring an archived
--   year or erroring on duplicates is untouched.)
-- ---------------------------------------------------------------------
create or replace function public.add_year(p_year text, p_default_days numeric default 30)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_role text; v_username text; v_year text; v_default numeric;
    emp record;
    v_running numeric;
    v_was_archived boolean;
    v_prev text;
begin
    select role, coalesce(username,'') into v_role, v_username
        from public.profiles where id = auth.uid();
    if v_role is distinct from 'admin' then raise exception 'هذه العملية مقصورة على المدير'; end if;
    v_year := trim(coalesce(p_year, ''));
    if v_year !~ '^\d{4}$' then raise exception 'يرجى إدخال سنة مالية صحيحة'; end if;

    if exists (select 1 from public.years where year = v_year and is_archived = false) then
        raise exception 'هذه السنة مسجلة مسبقاً';
    end if;
    v_was_archived := exists (select 1 from public.years where year = v_year and is_archived = true);
    v_default := coalesce(p_default_days, 30);

    -- Year roll-over: opening a brand-new year freezes the previous
    -- active year into its own isolated archive (separate from the new
    -- year). Never touches live rows; archive_year()/restore_year()
    -- remain the only way to hide/show a year in the UI.
    if not v_was_archived then
        select max(y.year) into v_prev
        from public.years y
        where y.is_archived = false and y.year < v_year;
        if v_prev is not null then
            insert into public.year_archives (year, frozen_by, snapshot)
            values (v_prev, v_username, public.build_year_archive_snapshot(v_prev))
            on conflict (year) do update
                set frozen_at = now(),
                    frozen_by = excluded.frozen_by,
                    snapshot   = excluded.snapshot;
            perform public.log_action(v_role, v_username, 'أرشفة سنة مالية',
                format('تم حفظ الأرشيف المنفصل للسنة %s تلقائياً عند فتح سنة %s', v_prev, v_year));
        end if;
    end if;

    if v_was_archived then
        update public.years set is_archived = false where year = v_year;
    else
        insert into public.years (year) values (v_year);
    end if;

    insert into public.employee_years (employee_id, year, added, deducted)
    select id, v_year, case when over_45 then 45 else v_default end, 0
        from public.employees where is_archived = false
    on conflict (employee_id, year) do nothing;

    for emp in select e.id, e.initial_carried_forward from public.employees e where e.is_archived = false loop
        select coalesce(emp.initial_carried_forward, 0)
             + coalesce(sum(coalesce(added,0) - coalesce(deducted,0)), 0)
          into v_running
          from public.employee_years where employee_id = emp.id;
        update public.employees set
            ceiled_cumulative_balance = ceil(v_running),
            carryover_ceiled_at_year = v_year
        where id = emp.id;
    end loop;

    perform public.log_action(v_role, v_username, 'إضافة سنة مالية', format('السنة: %s', v_year));
    return jsonb_build_object('years',
        coalesce((select jsonb_agg(year order by cast(year as integer))
                  from public.years where is_archived = false), '[]'::jsonb));
end;
$$;